// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartBarDuotone: typeof import('./src/components/icon/ChartBarDuotone.vue')['default']
    ExchangeDuotone: typeof import('./src/components/icon/ExchangeDuotone.vue')['default']
    HomeDashDuotone: typeof import('./src/components/icon/HomeDashDuotone.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletDuotone: typeof import('./src/components/icon/WalletDuotone.vue')['default']
  }
}
