// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconChartBarDuotone: typeof import('./components/icon/ChartBarDuotone.vue')['default']
    IconCoinConvertDuotone: typeof import('./components/icon/CoinConvertDuotone.vue')['default']
    IconExchangeDuotone: typeof import('./components/icon/ExchangeDuotone.vue')['default']
    IconHomeDashDuotone: typeof import('./components/icon/HomeDashDuotone.vue')['default']
    IconSearchLight: typeof import('./components/icon/SearchLight.vue')['default']
    IconUserDuotone: typeof import('./components/icon/UserDuotone.vue')['default']
    IconUserIcon: typeof import('./components/icon/UserDuotone.vue')['default']
    IconWalletDuotone: typeof import('./components/icon/WalletDuotone.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonLink: typeof import('@ionic/vue')['IonLink']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterLink: typeof import('@ionic/vue')['IonRouterLink']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSkeletonText: typeof import('@ionic/vue')['IonSkeletonText']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    ZInput: typeof import('./components/ZInput.vue')['default']
    ZTab: typeof import('./components/ZTab.vue')['default']
    ZTable: typeof import('./components/ZTable.vue')['default']
    ZTableRow: typeof import('./components/ZTableRow.vue')['default']
    ZTabs: typeof import('./components/ZTab.vue')['default']
  }
}
